### ISSUE TITLE
The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by ziga-hvalec** [googlemaps/react-native-navigation-sdk#309]
We're getting this error occasionally java.lang.IllegalStateException - The specified child already has a parent. You must call removeView() on the child's parent first. Nav sdk 0.6.1 on android only

```
 Fatal Exception: com.google.android.libraries.navigation.internal.mq.b: ab{property=ab{propertyType=ARROW_PAGER_ITEMS, layout=com.google.android.libraries.navigation.internal.tx.k, view=com.google.android.libraries.geo.navcore.ui.header.views.SwipeableHeaderView{bef9379 V.E...... ......ID 0,0-720,278 #7f0902fe app:id/step_cue_header viewInfo = }, propertyValue=[com.google.android.libraries.navigation.internal.ts.a@c86d8be, com.google.android.libraries.navigation.internal.ts.a@c685d1f, com.google.android.libraries.navigation.internal.ts.a@9c9486c, com.google.android.libraries.navigation.internal.ts.a@e4cee35, com.google.android.libraries.navigation.internal.ts.a@953c2ca]}, viewModel=com.google.android.libraries.navigation.internal.ts.d@357b6ac}
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5380)
       at android.view.ViewGroup.addView(ViewGroup.java:5201)
       at androidx.viewpager.widget.ViewPager.addView(ViewPager.java:1485)
       at android.view.ViewGroup.addView(ViewGroup.java:5136)
       at android.view.ViewGroup.addView(ViewGroup.java:5108)
       at com.google.android.libraries.navigation.internal.mo.b.instantiateItem(PG:7)
       at com.google.android.apps.gmm.base.views.viewpager.j.instantiateItem(PG:1)
       at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
       at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:669)
       at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
       at androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.java:1086)
       at androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(ViewPager.java:3097)
       at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:291)
       at com.google.android.apps.gmm.base.views.viewpager.j.c(PG:6)
       at com.google.android.apps.gmm.base.views.viewpager.i.onChanged(PG:2)
       at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
       at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:294)
       at com.google.android.libraries.navigation.internal.mo.b.b(PG:3)
       at com.google.android.apps.gmm.base.views.viewpager.g.a(PG:9)
       at com.google.android.libraries.navigation.internal.ms.a.g(PG:4)
       at com.google.android.libraries.navigation.internal.ms.c.b(PG:3)
       at com.google.android.libraries.navigation.internal.mn.bd.b(PG:3)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:10)
       at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
       at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
       at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
       at com.google.android.libraries.navigation.internal.mn.cc.q(PG:3)
       at com.google.android.libraries.navigation.internal.mn.cc.m(PG:1)
       at com.google.android.libraries.navigation.internal.mn.cs.a(PG:6)
       at com.google.android.libraries.navigation.internal.mn.aj.invoke(:2)
       at com.google.android.libraries.navigation.internal.mn.am.a(PG:2)
       at com.google.android.libraries.navigation.internal.vm.cs.run(PG:1)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
       at com.google.android.libraries.navigation.internal.if.b.run(PG:2)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
        
```

```
          Caused by java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5380)
       at android.view.ViewGroup.addView(ViewGroup.java:5201)
       at androidx.viewpager.widget.ViewPager.addView(ViewPager.java:1485)
       at android.view.ViewGroup.addView(ViewGroup.java:5136)
       at android.view.ViewGroup.addView(ViewGroup.java:5108)
       at com.google.android.libraries.navigation.internal.mo.b.instantiateItem(PG:7)
       at com.google.android.apps.gmm.base.views.viewpager.j.instantiateItem(PG:1)
       at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
       at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:669)
       at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
       at androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.java:1086)
       at androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(ViewPager.java:3097)
       at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:291)
       at com.google.android.apps.gmm.base.views.viewpager.j.c(PG:6)
       at com.google.android.apps.gmm.base.views.viewpager.i.onChanged(PG:2)
       at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
       at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:294)
       at com.google.android.libraries.navigation.internal.mo.b.b(PG:3)
       at com.google.android.apps.gmm.base.views.viewpager.g.a(PG:9)
       at com.google.android.libraries.navigation.internal.ms.a.g(PG:4)
       at com.google.android.libraries.navigation.internal.ms.c.b(PG:3)
       at com.google.android.libraries.navigation.internal.mn.bd.b(PG:3)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:10)
       at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
       at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
       at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
       at com.google.android.libraries.navigation.internal.mn.cc.q(PG:3)
       at com.google.android.libraries.navigation.internal.mn.cc.m(PG:1)
       at com.google.android.libraries.navigation.internal.mn.cs.a(PG:6)
       at com.google.android.libraries.navigation.internal.mn.aj.invoke(:2)
       at com.google.android.libraries.navigation.internal.mn.am.a(PG:2)
       at com.google.android.libraries.navigation.internal.vm.cs.run(PG:1)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
       at com.google.android.libraries.navigation.internal.if.b.run(PG:2)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
        
```

**Comment by caio1985** [comment]
Ack! @illuminati1911 can you please take a look into this? @jokerttu FYI.

**Comment by jokerttu** [comment]
I’ve marked this as the highest priority. We need to find a way to reproduce the issue in order to identify a fix. This is an internal exception within the navigation SDK, but it’s most likely related to how views are initialized in the React Native package implementation.

**Comment by sr1k3sh** [comment]
> We're getting this error occasionally java.lang.IllegalStateException - The specified child already has a parent. You must call removeView() on the child's parent first. Nav sdk 0.6.1 on android only
> 
> ```
>  Fatal Exception: com.google.android.libraries.navigation.internal.mq.b: ab{property=ab{propertyType=ARROW_PAGER_ITEMS, layout=com.google.android.libraries.navigation.internal.tx.k, view=com.google.android.libraries.geo.navcore.ui.header.views.SwipeableHeaderView{bef9379 V.E...... ......ID 0,0-720,278 #7f0902fe app:id/step_cue_header viewInfo = }, propertyValue=[com.google.android.libraries.navigation.internal.ts.a@c86d8be, com.google.android.libraries.navigation.internal.ts.a@c685d1f, com.google.android.libraries.navigation.internal.ts.a@9c9486c, com.google.android.libraries.navigation.internal.ts.a@e4cee35, com.google.android.libraries.navigation.internal.ts.a@953c2ca]}, viewModel=com.google.android.libraries.navigation.internal.ts.d@357b6ac}
>        at android.view.ViewGroup.addViewInner(ViewGroup.java:5380)
>        at android.view.ViewGroup.addView(ViewGroup.java:5201)
>        at androidx.viewpager.widget.ViewPager.addView(ViewPager.java:1485)
>        at android.view.ViewGroup.addView(ViewGroup.java:5136)
>        at android.view.ViewGroup.addView(ViewGroup.java:5108)
>        at com.google.android.libraries.navigation.internal.mo.b.instantiateItem(PG:7)
>        at com.google.android.apps.gmm.base.views.viewpager.j.instantiateItem(PG:1)
>        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
>        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
>        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:669)
>        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
>        at androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.java:1086)
>        at androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(ViewPager.java:3097)
>        at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:291)
>        at com.google.android.apps.gmm.base.views.viewpager.j.c(PG:6)
>        at com.google.android.apps.gmm.base.views.viewpager.i.onChanged(PG:2)
>        at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
>        at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:294)
>        at com.google.android.libraries.navigation.internal.mo.b.b(PG:3)
>        at com.google.android.apps.gmm.base.views.viewpager.g.a(PG:9)
>        at com.google.android.libraries.navigation.internal.ms.a.g(PG:4)
>        at com.google.android.libraries.navigation.internal.ms.c.b(PG:3)
>        at com.google.android.libraries.navigation.internal.mn.bd.b(PG:3)
>        at com.google.android.libraries.navigation.internal.mn.cc.r(PG:10)
>        at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
>        at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
>        at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
>        at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
>        at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
>        at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
>        at com.google.android.libraries.navigation.internal.mn.cc.q(PG:3)
>        at com.google.android.libraries.navigation.internal.mn.cc.m(PG:1)
>        at com.google.android.libraries.navigation.internal.mn.cs.a(PG:6)
>        at com.google.android.libraries.navigation.internal.mn.aj.invoke(:2)
>        at com.google.android.libraries.navigation.internal.mn.am.a(PG:2)
>        at com.google.android.libraries.navigation.internal.vm.cs.run(PG:1)
>        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
>        at com.google.android.libraries.navigation.internal.if.b.run(PG:2)
>        at android.os.Handler.handleCallback(Handler.java:958)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loopOnce(Looper.java:257)
>        at android.os.Looper.loop(Looper.java:368)
>        at android.app.ActivityThread.main(ActivityThread.java:8839)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
>         
> ```
> 
> ```
>           Caused by java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
>        at android.view.ViewGroup.addViewInner(ViewGroup.java:5380)
>        at android.view.ViewGroup.addView(ViewGroup.java:5201)
>        at androidx.viewpager.widget.ViewPager.addView(ViewPager.java:1485)
>        at android.view.ViewGroup.addView(ViewGroup.java:5136)
>        at android.view.ViewGroup.addView(ViewGroup.java:5108)
>        at com.google.android.libraries.navigation.internal.mo.b.instantiateItem(PG:7)
>        at com.google.android.apps.gmm.base.views.viewpager.j.instantiateItem(PG:1)
>        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
>        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
>        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:669)
>        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
>        at androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.java:1086)
>        at androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(ViewPager.java:3097)
>        at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:291)
>        at com.google.android.apps.gmm.base.views.viewpager.j.c(PG:6)
>        at com.google.android.apps.gmm.base.views.viewpager.i.onChanged(PG:2)
>        at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
>        at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:294)
>        at com.google.android.libraries.navigation.internal.mo.b.b(PG:3)
>        at com.google.android.apps.gmm.base.views.viewpager.g.a(PG:9)
>        at com.google.android.libraries.navigation.internal.ms.a.g(PG:4)
>        at com.google.android.libraries.navigation.internal.ms.c.b(PG:3)
>        at com.google.android.libraries.navigation.internal.mn.bd.b(PG:3)
>        at com.google.android.libraries.navigation.internal.mn.cc.r(PG:10)
>        at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
>        at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
>        at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
>        at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
>        at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
>        at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
>        at com.google.android.libraries.navigation.internal.mn.cc.q(PG:3)
>        at com.google.android.libraries.navigation.internal.mn.cc.m(PG:1)
>        at com.google.android.libraries.navigation.internal.mn.cs.a(PG:6)
>        at com.google.android.libraries.navigation.internal.mn.aj.invoke(:2)
>        at com.google.android.libraries.navigation.internal.mn.am.a(PG:2)
>        at com.google.android.libraries.navigation.internal.vm.cs.run(PG:1)
>        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
>        at com.google.android.libraries.navigation.internal.if.b.run(PG:2)
>        at android.os.Handler.handleCallback(Handler.java:958)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loopOnce(Looper.java:257)
>        at android.os.Looper.loop(Looper.java:368)
>        at android.app.ActivityThread.main(ActivityThread.java:8839)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
>         
> ```


I'm also facing this issue. for me every time i close the view and reopen, i get mentioned issue `Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                                                    	... 46 more`

**Comment by ziga-hvalec** [comment]
Still happening on 0.8.1

**Comment by ziga-hvalec** [comment]
Has this been fixed. Any update on this?

**Comment by jokerttu** [comment]
I haven't been able to re-produce this. Could you please provide minimun example where this happen.

**Comment by jokerttu** [comment]
@sr1k3sh 
Same question for you, what view pager component you are using, could you provide example of the page hierarchy where this issue is visible.

**Comment by ziga-hvalec** [comment]
I'm not using any pager component. I do have react-native-pager-view installed because it's required by some other dependency, can't remember which tho.

```
"react-native-pager-view": "6.3.3",
```

**Comment by ziga-hvalec** [comment]
Hi. Any update on this?

**Comment by sr1k3sh** [comment]
> [@sr1k3sh](https://github.com/sr1k3sh) Same question for you, what view pager component you are using, could you provide example of the page hierarchy where this issue is visible.

@jokerttu  I have used the navsdk on 
```
const Stack = createNativeStackNavigator()

<Stack.Navigator
      screenOptions={{
        headerShown: false,
        gestureEnabled: false,
      }}
    >
<Stack.Screen name='navsdk' component={NavsdkContainer} />
</Stack.Navigator>Ï

``` 

And `NavsdkContainer` is like 

export const NavsdkContainer = ({ }: Props) => {
return (
<NavigationProvider
      termsAndConditionsDialogOptions={termsAndConditionsDialogOptions}
      taskRemovedBehavior={TaskRemovedBehavior.CONTINUE_SERVICE}
    >
     <View style={{
          flex: 1,
        }}>
          <NavigationView
              style={{
                height: '100%',
                width: '100%',
              }}
    
              mapViewCallbacks={mapViewCallbacks}
              onMapViewControllerCreated={setMapViewController}
              onNavigationViewControllerCreated={setNavigationViewController}
            />
          </View>
    </View>
    </NavigationProvider>Ï
)
}

However after adding cleanup logic i couldn't reproduce the issue, but got report about crashing in real device with mentioned error

**Comment by jokerttu** [comment]
I haven't been able to fix this yet, but working on the solution. I was able to re-produce similar issues with react-native-pager-view package.

**Comment by ziga-hvalec** [comment]
any update?

**Comment by jokerttu** [comment]
@ziga-hvalec process on updating view manager layer is on going while implementinhg support for new react native module architecture.
There are still work to do and I cannot give estimate just yet, but work is ongoing and proceeding; this should fix a lot of issues and also give support to use package better with expo projects.

**Comment by jokerttu** [comment]
**Status Update**: The migration to React Native's new architecture, incorporating Fabric and TurboModules, is currently in progress. Before publishing this version, we will ensure that both platforms operate as expected without introducing new bugs. Once the conversion to new architecture is complete, the package will be released as a Release Candidate (RC) to facilitate thorough testing.

**Comment by jokerttu** [comment]
Hi,
Fix (for old architecture) coming on PR: 
https://github.com/googlemaps/react-native-navigation-sdk/pull/473
Will be landed after tests pass for each supported RN version.
